name: "Build and Export"

on: push

jobs:
  build:
    name: Build - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            output: librust.so

          - os-name: Android
            runs-on: ubuntu-24.04
            target: aarch64-linux-android
            output: librust.so
            toolchain: nightly

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            output: rust.dll

          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin
            output: librust.dylib
        include:
          - command: both
            toolchain: stable

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          working-directory: rust
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          toolchain: ${{ matrix.platform.toolchain }}
          strip: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.os-name }}
          path: rust/target/${{ matrix.platform.target }}/release/${{ matrix.platform.output }}

  # export:
  #   needs: Build - ${{ matrix.platform.os-name }}
  #   strategy:
  #     matrix:
  #       platform:
  #         - os-name: Linux-x86_64
  #           runs-on: ubuntu-24.04
  #           target: x86_64-unknown-linux-musl
  #           command: both

  #         - os-name: Android
  #           runs-on: ubuntu-24.04
  #           target: aarch64-linux-android
  #           command: both

  #         - os-name: Windows-x86_64
  #           runs-on: windows-latest
  #           target: x86_64-pc-windows-msvc
  #           command: both

  #         - os-name: macOS-x86_64
  #           runs-on: macOS-latest
  #           target: x86_64-apple-darwin
  #           command: both